In [16]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [17]:
df = pd.read_csv('../Data/processed/Gurgaon_cleaned_final.csv')

In [18]:
df.head()

,property_type,society,sector,price,price_per_sqft,area,bedRoom,bathroom,balcony,floorNum,agePossession,built_up_area,study room,servant room,pooja room,store room,others,furnishing_type,luxury_score
0,flat,maa bhagwati residency,sector 7,0.45,5000.0,900.0,2,2,1,4.0,Relatively New,1066.350711,0,0,0,0,0,2,28
1,flat,apna enclave,sector 5,0.50,7692.0,650.0,2,2,1,1.0,Old Property,770.142180,0,0,0,0,0,0,37
2,flat,tulsiani easy in homes,sector 48,0.40,6722.0,595.0,2,2,3,12.0,New Property,704.976303,0,0,0,0,0,2,36
3,flat,smart world orchard,sector 61,1.47,12250.0,1200.0,2,2,2,2.0,Under Construction,1421.800948,1,0,0,0,0,2,76
4,flat,parkwood westend,sector 92,0.70,5204.0,1345.0,2,2,3,5.0,Under Construction,1185.022026,1,0,0,0,0,2,0

In [19]:
df.shape

(3853, 19)

In [20]:
df.sector.unique()

array(['sector 7', 'sector 5', 'sector 48', 'sector 61', 'sector 92',
       'sector 36', 'sector 102', 'sector 104', 'sector 88b', 'sector 78',
       'sector 81', 'sector 79', 'sector 33', 'sector 90', 'sector 108',
       'sector 62', 'sector-33 sohna', 'sector 89', 'sector 113',
       'sector 65', 'sector 37c', 'sector 3', 'sector 1', 'sector 43',
       'sector 88a', 'sector 68', 'sector 109', 'sector 106', 'sector 82',
       'sector 85', 'sector 82a', 'sector 28', 'sector 10a',
       'sector 1a imt manesar', 'sector 21', 'sector 84', 'sector 71',
       'sector 77', 'sector 37d', 'sector 67a', 'sector 57', 'sector 95',
       'sector 99a', 'sector 103', 'sector 49', 'sector 30', 'sector 66',
       'sector 15 part 1', 'laxman vihar', 'sector 22', 'sector 63a',
       'sector 86', 'sector 52', 'sector 67', 'sector 107', 'sector 12a',
       'sector 12A', 'sector 2', 'sector 9', 'sector 9B', 'sector 95a',
       'sector 99', 'sector 18', 'sector 91', 'sector 70', 'sector 70a',
       'sector 47', 'sector 53', 'sector 4', 'sector 54', 'sector 111',
       'chakkarpur', 'sector 41', 'sector 12', 'sector 73',
       'sector 36 sohna', 'sector 56', 'sector 83', 'sector 72',
       'sector 1 imt manesar', 'sector 69', 'sector 63', 'sector 110',
       'sector 45', 'sector-11 sohna', 'sector 9a', 'sector 14',
       'sector 50', 'sector 25', 'sector 59', 'dlf phase 3', 'sector 38',
       'sector 15', 'sector 24', 'sector 112', 'sector 74', 'sector 60',
       'sector 51', 'sector 110 a', 'sector 39', 'sector 1A IMT Manesar',
       'sector 58', 'sector 80', 'sector 55', 'sector 93', 'sector 23a',
       'sector 36a', 'sector 76', 'sector 31', 'sector 89 a',
       'sector unknown', 'sector 11', 'sector 32', 'sector 10',
       'sector-2 sohna', 'sector 37a', 'sector 23A', 'mehrauli  road',
       'laxman vihar phase 2', 'sector-5 sohna', 'dayanand colony',
       'new palam vihar phase 2', 'sector-35 sohna',
       'sector 4 urban estate', 'sector 105', 'sector 40', 'sector 8',
       'godrej aria , sector 79 ,', 'sector 21a faridabad', 'sector 26',
       'b block sushant lok phase 1', 'hsiidc plot sector 1 imt manesar',
       'sector 15 part 2', 'c block sushant lok phase 1', 'sector 23',
       'sector 17c', 'not gurgaon', 'sector 6', 'sector 9b',
       'urban estate, sector 5', 'part 3 sector 5', 'sector 13',
       'sector 17a', 'block g sector-57', 'sector 17', 'sector 3a',
       'anand garden, sector-105', 'sector 37b',
       'g block dlf city phase 1', 'sector 35', 'sector 29', 'sector 17b',
       'sector 27', 'sector 46', 'b1 block sector 57', 'sector 42'],
      dtype=object)

In [21]:
df[df['sector'].isin(['sector unknown', 'not gurgaon'])]

,property_type,society,sector,price,price_per_sqft,area,bedRoom,bathroom,balcony,floorNum,agePossession,built_up_area,study room,servant room,pooja room,store room,others,furnishing_type,luxury_score
2032,flat,dlf 76,sector unknown,4.00,11428.000000,3500.0,4,4,2,4.0,Under Construction,4146.919431,1,1,0,0,0,0,101
2782,flat,takshila heights sector 37 c,sector unknown,0.67,5583.000000,1200.0,2,2,2,3.0,Relatively New,1057.268722,0,0,0,0,0,2,23
2874,flat,green court,sector unknown,0.38,5507.000000,690.0,2,2,1,7.0,Under Construction,817.535545,0,0,0,0,0,2,35
2939,flat,sare homes,sector unknown,0.85,4786.000000,1776.0,4,4,3,3.0,Moderately Old,1564.757709,0,0,0,0,0,2,0
3011,house,sector 37,sector unknown,0.55,7290.000000,754.0,2,1,1,1.0,New Property,83.000000,0,0,0,1,0,2,90
3094,house,independent,not gurgaon,1.00,11111.000000,900.0,4,3,3+,4.0,Relatively New,179.856115,0,0,0,0,1,2,0
3121,house,independent,not gurgaon,0.15,2296.000000,653.0,2,1,0,1.0,Old Property,134.892086,0,0,0,0,0,2,0
3122,house,rajendra park sec 105,sector unknown,0.80,8888.000000,900.0,9,5,3+,3.0,Old Property,990.000000,0,0,0,0,0,2,0
3174,house,independent,not gurgaon,2.30,2820.701496,8154.0,6,6,0,0.0,Old Property,1629.496403,0,0,0,0,1,2,41
3184,house,dlf garden city floors,not gurgaon,4.00,17817.000000,2245.0,7,7,3+,4.0,New Property,4037.769784,0,0,0,0,0,2,45
3247,house,independent,not gurgaon,0.52,5778.000000,900.0,3,2,2,2.0,New Property,179.856115,0,0,0,0,0,2,0
3360,house,independent,not gurgaon,0.18,4000.000000,450.0,2,1,1,1.0,Relatively New,809.352518,0,0,0,0,0,2,0
3370,house,independent,not gurgaon,0.50,3704.000000,1350.0,5,2,0,2.0,Relatively New,1350.000000,0,0,0,0,0,2,0
3400,house,independent,not gurgaon,1.50,16667.000000,900.0,9,3,3+,3.0,Relatively New,1066.350711,0,0,0,0,0,2,0
3452,house,independent,not gurgaon,0.13,1649.000000,788.0,1,1,0,0.0,Relatively New,933.649289,0,0,0,0,0,2,0
3480,house,independent,sector unknown,1.70,18889.000000,900.0,5,4,3+,3.0,Moderately Old,61.000000,0,0,0,0,0,2,34
3593,house,independent,sector unknown,0.53,7095.046854,747.0,2,1,1,1.0,New Property,84.000000,0,0,0,1,0,0,128
3847,house,silverglades tarudhan valley golf resort,not gurgaon,3.05,12551.000000,2430.0,3,3,2,2.0,Moderately Old,2430.000000,1,1,1,0,1,1,160
3852,house,silverglades tarudhan valley golf resort,not gurgaon,3.60,14815.000000,2430.0,3,3,2,2.0,Moderately Old,2430.000000,1,1,1,0,1,1,160

In [22]:
sector_map = {
    'laxman vihar': 'sector 4',
    'laxman vihar phase 2': 'sector 4',
    'dayanand colony': 'sector 6',
    'chakkarpur': 'sector 28',
    'dlf phase 3': 'sector 24',
    'mehrauli  road': 'sector 14',
    'new palam vihar phase 2': 'sector 110',
    'b block sushant lok phase 1': 'sector 43',
    'c block sushant lok phase 1': 'sector 43',
    'g block dlf city phase 1': 'sector 26',
    'urban estate, sector 5': 'sector 5',
    'part 3 sector 5': 'sector 5',
    'godrej aria , sector 79 ,': 'sector 79',
    'hsiidc plot sector 1 imt manesar': 'sector 1a imt manesar',
    'anand garden, sector-105': 'sector 105',
    'block g sector-57': 'sector 57',
    'b1 block sector 57': 'sector 57',
    'sector unknown': np.nan,
    'not gurgaon': np.nan,
    'sector 21a faridabad': 'sector 21'
}

df['sector'] = df['sector'].replace(sector_map)

In [23]:
df.sector.unique()

array(['sector 7', 'sector 5', 'sector 48', 'sector 61', 'sector 92',
       'sector 36', 'sector 102', 'sector 104', 'sector 88b', 'sector 78',
       'sector 81', 'sector 79', 'sector 33', 'sector 90', 'sector 108',
       'sector 62', 'sector-33 sohna', 'sector 89', 'sector 113',
       'sector 65', 'sector 37c', 'sector 3', 'sector 1', 'sector 43',
       'sector 88a', 'sector 68', 'sector 109', 'sector 106', 'sector 82',
       'sector 85', 'sector 82a', 'sector 28', 'sector 10a',
       'sector 1a imt manesar', 'sector 21', 'sector 84', 'sector 71',
       'sector 77', 'sector 37d', 'sector 67a', 'sector 57', 'sector 95',
       'sector 99a', 'sector 103', 'sector 49', 'sector 30', 'sector 66',
       'sector 15 part 1', 'sector 4', 'sector 22', 'sector 63a',
       'sector 86', 'sector 52', 'sector 67', 'sector 107', 'sector 12a',
       'sector 12A', 'sector 2', 'sector 9', 'sector 9B', 'sector 95a',
       'sector 99', 'sector 18', 'sector 91', 'sector 70', 'sector 70a',
       'sector 47', 'sector 53', 'sector 54', 'sector 111', 'sector 41',
       'sector 12', 'sector 73', 'sector 36 sohna', 'sector 56',
       'sector 83', 'sector 72', 'sector 1 imt manesar', 'sector 69',
       'sector 63', 'sector 110', 'sector 45', 'sector-11 sohna',
       'sector 9a', 'sector 14', 'sector 50', 'sector 25', 'sector 59',
       'sector 24', 'sector 38', 'sector 15', 'sector 112', 'sector 74',
       'sector 60', 'sector 51', 'sector 110 a', 'sector 39',
       'sector 1A IMT Manesar', 'sector 58', 'sector 80', 'sector 55',
       'sector 93', 'sector 23a', 'sector 36a', 'sector 76', 'sector 31',
       'sector 89 a', nan, 'sector 11', 'sector 32', 'sector 10',
       'sector-2 sohna', 'sector 37a', 'sector 23A', 'sector-5 sohna',
       'sector 6', 'sector-35 sohna', 'sector 4 urban estate',
       'sector 105', 'sector 40', 'sector 8', 'sector 26',
       'sector 15 part 2', 'sector 23', 'sector 17c', 'sector 9b',
       'sector 13', 'sector 17a', 'sector 17', 'sector 3a', 'sector 37b',
       'sector 35', 'sector 29', 'sector 17b', 'sector 27', 'sector 46',
       'sector 42'], dtype=object)

In [24]:
import re
import numpy as np

def extract_sector_number(x):
    if pd.isna(x):
        return np.nan

    x = str(x).lower()

    match = re.search(r'sector[\s\-]*(\d+)', x)

    if match:
        return int(match.group(1))

    return np.nan

df['sector'] = df['sector'].apply(extract_sector_number)

In [25]:
df.sector.unique()

array([  7.,   5.,  48.,  61.,  92.,  36., 102., 104.,  88.,  78.,  81.,
        79.,  33.,  90., 108.,  62.,  89., 113.,  65.,  37.,   3.,   1.,
        43.,  68., 109., 106.,  82.,  85.,  28.,  10.,  21.,  84.,  71.,
        77.,  67.,  57.,  95.,  99., 103.,  49.,  30.,  66.,  15.,   4.,
        22.,  63.,  86.,  52., 107.,  12.,   2.,   9.,  18.,  91.,  70.,
        47.,  53.,  54., 111.,  41.,  73.,  56.,  83.,  72.,  69., 110.,
        45.,  11.,  14.,  50.,  25.,  59.,  24.,  38., 112.,  74.,  60.,
        51.,  39.,  58.,  80.,  55.,  93.,  23.,  76.,  31.,  nan,  32.,
         6.,  35., 105.,  40.,   8.,  26.,  17.,  13.,  29.,  27.,  46.,
        42.])

In [26]:
df.head(50)

,property_type,society,sector,price,price_per_sqft,area,bedRoom,bathroom,balcony,floorNum,agePossession,built_up_area,study room,servant room,pooja room,store room,others,furnishing_type,luxury_score
0,flat,maa bhagwati residency,7.0,0.45,5000.000000,900.0,2,2,1,4.0,Relatively New,1066.350711,0,0,0,0,0,2,28
1,flat,apna enclave,5.0,0.50,7692.000000,650.0,2,2,1,1.0,Old Property,770.142180,0,0,0,0,0,0,37
2,flat,tulsiani easy in homes,48.0,0.40,6722.000000,595.0,2,2,3,12.0,New Property,704.976303,0,0,0,0,0,2,36
3,flat,smart world orchard,61.0,1.47,12250.000000,1200.0,2,2,2,2.0,Under Construction,1421.800948,1,0,0,0,0,2,76
4,flat,parkwood westend,92.0,0.70,5204.000000,1345.0,2,2,3,5.0,Under Construction,1185.022026,1,0,0,0,0,2,0
5,flat,signature global infinity mall,36.0,0.41,6269.000000,654.0,2,2,3,3.0,Relatively New,654.000000,0,0,0,0,0,2,0
6,flat,the cocoon,102.0,2.00,13333.000000,1500.0,3,3,3,5.0,New Property,1321.585903,0,0,0,0,0,2,0
7,flat,ats triumph,104.0,1.80,7860.000000,2290.0,3,4,3,14.0,New Property,2713.270142,0,0,0,0,0,2,60
8,flat,vatika xpressions,88.0,1.10,8148.000000,1350.0,2,4,3+,2.0,Under Construction,1350.000000,1,0,0,0,0,2,58
9,flat,raheja revanta,78.0,4.75,16885.000000,2813.0,3,3,2,31.0,Under Construction,2813.000000,0,1,0,0,0,2,100
10,flat,signature global city 81,81.0,0.96,9767.000000,983.0,2,2,2,1.0,Under Construction,1273.696682,0,0,0,0,0,2,49
11,flat,hcbs sports ville,48.0,0.29,5587.000000,519.0,2,2,1,4.0,Relatively New,614.928910,0,0,0,0,0,2,44
12,flat,supertech araville,79.0,1.35,6940.000000,1945.0,3,3,3,4.0,Relatively New,2304.502370,0,0,0,0,0,2,0
13,flat,godrej,33.0,0.95,6859.000000,1385.0,2,2,3+,3.0,Under Construction,1220.264317,0,0,0,0,0,2,0
14,flat,shree vardhman flora,90.0,0.70,5384.000000,1300.0,2,2,3,13.0,New Property,1145.374449,1,0,0,0,0,2,15
15,flat,sobha city,108.0,3.95,16859.000000,2343.0,4,5,3,25.0,Relatively New,2343.000000,0,0,0,0,0,2,0
16,flat,senate court,62.0,0.90,14084.000000,639.0,1,1,0,0.0,Relatively New,639.000000,0,0,0,0,0,2,0
17,flat,shapoorji pallonji joyville gurugram,102.0,1.05,11475.000000,915.0,2,2,2,0.0,Under Construction,1084.123223,0,0,0,0,0,2,49
18,flat,central park flower valley,33.0,2.20,10476.000000,2100.0,3,3,3,12.0,New Property,1850.220264,0,1,0,0,0,0,49
19,flat,smart world gems,89.0,1.01,9156.000000,1103.0,2,2,2,4.0,Under Construction,1306.872038,1,0,0,0,0,2,38
20,flat,bestech altura,79.0,1.85,8604.000000,2150.0,3,4,3+,11.0,New Property,1894.273128,0,1,0,0,0,2,49
21,flat,smart world gems,89.0,0.86,7796.000000,1103.0,2,3,3,4.0,Under Construction,971.806167,0,0,0,0,0,2,0
22,flat,emaar imperial gardens,102.0,1.85,9135.000000,2025.0,3,3,3+,0.0,Relatively New,2399.289100,0,1,0,0,0,0,95
23,flat,la vida by tata housing,113.0,2.85,12855.000000,2217.0,3,3,3+,10.0,New Property,2217.000000,0,1,0,0,0,2,72
24,flat,the serenas,36.0,0.42,7910.000000,531.0,2,2,1,3.0,Relatively New,629.146919,0,0,0,0,0,2,0
25,flat,m3m golfestate,65.0,6.15,18331.000000,3355.0,3,4,2,20.0,Relatively New,3355.000000,0,0,0,0,0,2,0
26,flat,central park resort belgravia residences,48.0,6.25,24300.155521,2572.0,3,5,3+,5.0,Moderately Old,3412.322275,0,1,0,0,0,0,49
27,flat,apex builders,37.0,0.42,5600.000000,750.0,2,2,2,4.0,Relatively New,888.625592,0,0,0,0,0,2,42
28,flat,godrej habitat,3.0,1.35,12784.000000,1056.0,2,2,0,4.0,Under Construction,1056.000000,0,0,0,0,0,2,0
29,flat,ompee k s residency,1.0,1.60,2992.891882,5346.0,2,2,2,1.0,Relatively New,78.199052,0,0,0,0,0,2,0
30,flat,bhawna cghs,43.0,3.25,10156.000000,3200.0,4,4,3+,12.0,Moderately Old,3200.000000,0,0,1,0,0,0,119
31,flat,adani aangan arcade,88.0,0.45,7194.000000,626.0,2,2,1,8.0,New Property,741.102167,0,0,0,0,0,2,14
32,flat,sare green parc,92.0,0.85,6538.000000,1300.0,3,2,2,20.0,Relatively New,1300.000000,0,0,0,0,0,2,0
33,flat,shree vardhman flora,90.0,0.75,5769.000000,1300.0,2,2,3,8.0,Relatively New,1540.284360,0,0,0,0,0,2,0
34,flat,supertech hues,68.0,0.82,6950.000000,1180.0,2,2,3+,21.0,Under Construction,1039.647577,0,0,0,0,1,2,72
35,flat,chintels paradiso,109.0,1.80,8866.000000,2030.0,3,3,2,0.0,Moderately Old,1.979044,0,1,0,0,0,2,83
36,flat,breez global hill view,48.0,0.30,5403.000000,555.0,2,2,2,6.0,New Property,1.979044,0,0,0,0,0,2,109
37,flat,ild greens,37.0,0.78,5714.000000,1365.0,2,2,3,1.0,Moderately Old,1068.100000,0,0,0,0,0,0,103
38,flat,ansal sushant lok ci,43.0,2.00,15151.000000,1320.0,3,3,2,1.0,Old Property,1563.981043,0,1,0,0,0,1,15
39,flat,ashiana mulberry,48.0,0.74,6200.000000,1194.0,2,2,3+,12.0,New Property,1433.649289,0,0,0,0,0,2,67
40,flat,godrej meridien,106.0,3.20,16000.000000,2000.0,3,3,3+,6.0,Under Construction,2372.037915,0,1,0,0,0,2,49
41,flat,mapsko casa bella,82.0,1.30,6378.000000,2038.0,4,4,3+,1.0,Relatively New,1726.872247,0,1,0,0,0,2,130
42,flat,pooja apartment,5.0,0.25,3571.000000,700.0,2,2,2,2.0,Relatively New,829.383886,0,0,0,0,0,2,0
43,flat,signature global park,48.0,0.95,7846.000000,1211.0,3,2,3+,1.0,Relatively New,1210.723472,0,0,0,0,0,2,46
44,flat,dlf new town heights,90.0,1.99,7297.000000,2727.0,4,4,3+,9.0,Relatively New,3231.042654,0,1,1,0,0,0,102
45,flat,paras dews,106.0,1.05,7581.000000,1385.0,2,2,2,5.0,New Property,1640.995261,0,0,0,0,0,2,97
46,flat,godrej air,85.0,1.83,10005.000000,1829.0,3,3,3+,18.0,Under Construction,2167.061611,0,0,0,0,0,2,110
47,flat,dlf the primus,82.0,2.25,10714.000000,2100.0,3,3,3+,29.0,Relatively New,2488.151659,0,1,0,0,0,1,72
48,flat,emaar mgf emerald floors premier,65.0,2.80,16969.000000,1650.0,3,3,3+,3.0,Relatively New,1650.000000,1,1,0,0,0,0,38
49,flat,dlf regency park,28.0,1.60,14545.000000,1100.0,2,2,2,3.0,Relatively New,1303.317536,0,0,0,0,0,2,52

In [27]:
df[df.sector.isnull()]

,property_type,society,sector,price,price_per_sqft,area,bedRoom,bathroom,balcony,floorNum,agePossession,built_up_area,study room,servant room,pooja room,store room,others,furnishing_type,luxury_score
2032,flat,dlf 76,NaN,4.00,11428.000000,3500.0,4,4,2,4.0,Under Construction,4146.919431,1,1,0,0,0,0,101
2782,flat,takshila heights sector 37 c,NaN,0.67,5583.000000,1200.0,2,2,2,3.0,Relatively New,1057.268722,0,0,0,0,0,2,23
2874,flat,green court,NaN,0.38,5507.000000,690.0,2,2,1,7.0,Under Construction,817.535545,0,0,0,0,0,2,35
2939,flat,sare homes,NaN,0.85,4786.000000,1776.0,4,4,3,3.0,Moderately Old,1564.757709,0,0,0,0,0,2,0
3011,house,sector 37,NaN,0.55,7290.000000,754.0,2,1,1,1.0,New Property,83.000000,0,0,0,1,0,2,90
3094,house,independent,NaN,1.00,11111.000000,900.0,4,3,3+,4.0,Relatively New,179.856115,0,0,0,0,1,2,0
3121,house,independent,NaN,0.15,2296.000000,653.0,2,1,0,1.0,Old Property,134.892086,0,0,0,0,0,2,0
3122,house,rajendra park sec 105,NaN,0.80,8888.000000,900.0,9,5,3+,3.0,Old Property,990.000000,0,0,0,0,0,2,0
3174,house,independent,NaN,2.30,2820.701496,8154.0,6,6,0,0.0,Old Property,1629.496403,0,0,0,0,1,2,41
3184,house,dlf garden city floors,NaN,4.00,17817.000000,2245.0,7,7,3+,4.0,New Property,4037.769784,0,0,0,0,0,2,45
3247,house,independent,NaN,0.52,5778.000000,900.0,3,2,2,2.0,New Property,179.856115,0,0,0,0,0,2,0
3360,house,independent,NaN,0.18,4000.000000,450.0,2,1,1,1.0,Relatively New,809.352518,0,0,0,0,0,2,0
3370,house,independent,NaN,0.50,3704.000000,1350.0,5,2,0,2.0,Relatively New,1350.000000,0,0,0,0,0,2,0
3400,house,independent,NaN,1.50,16667.000000,900.0,9,3,3+,3.0,Relatively New,1066.350711,0,0,0,0,0,2,0
3452,house,independent,NaN,0.13,1649.000000,788.0,1,1,0,0.0,Relatively New,933.649289,0,0,0,0,0,2,0
3480,house,independent,NaN,1.70,18889.000000,900.0,5,4,3+,3.0,Moderately Old,61.000000,0,0,0,0,0,2,34
3593,house,independent,NaN,0.53,7095.046854,747.0,2,1,1,1.0,New Property,84.000000,0,0,0,1,0,0,128
3847,house,silverglades tarudhan valley golf resort,NaN,3.05,12551.000000,2430.0,3,3,2,2.0,Moderately Old,2430.000000,1,1,1,0,1,1,160
3852,house,silverglades tarudhan valley golf resort,NaN,3.60,14815.000000,2430.0,3,3,2,2.0,Moderately Old,2430.000000,1,1,1,0,1,1,160

In [28]:
df.loc[2032, 'sector'] = 76
df.loc[2782, 'sector'] = 37
df.loc[2874, 'sector'] = 90
df.loc[2939, 'sector'] = 92
df.loc[2977, 'sector'] = 200
df.loc[3011, 'sector'] = 37
df.loc[3094, 'sector'] = 200
df.loc[3121, 'sector'] = 200
df.loc[3122, 'sector'] = 105
df.loc[3174, 'sector'] = 200
df.loc[3184, 'sector'] = 91
df.loc[3247, 'sector'] = 200
df.loc[3360, 'sector'] = 200
df.loc[3370, 'sector'] = 200
df.loc[3400, 'sector'] = 200
df.loc[3452, 'sector'] = 200
df.loc[3480, 'sector'] = 200
df.loc[3593, 'sector'] = 200
df.loc[3847, 'sector'] = 64
df.loc[3852, 'sector'] = 64

In [29]:
df['balcony'] = df['balcony'].replace('3+', 3).astype(int)

In [30]:
df.isnull().sum()

property_type      0
society            0
sector             0
price              0
price_per_sqft     0
area               0
bedRoom            0
bathroom           0
balcony            0
floorNum           0
agePossession      0
built_up_area      0
study room         0
servant room       0
pooja room         0
store room         0
others             0
furnishing_type    0
luxury_score       0
dtype: int64

In [31]:
df.agePossession.value_counts()

agePossession
Relatively New        1834
Moderately Old         699
New Property           641
Old Property           381
Under Construction     298
Name: count, dtype: int64

In [32]:
df.replace({'agePossession': {'undefined': df.agePossession.mode()[0]}}, inplace=True)

In [33]:
df.agePossession.value_counts()

agePossession
Relatively New        1834
Moderately Old         699
New Property           641
Old Property           381
Under Construction     298
Name: count, dtype: int64

In [34]:
def mode_based_imputation(row):
    if row['agePossession'] == 'Undefined':
        mode_value = df[(df['sector'] == row['sector']) & 
                        (df['property_type'] == row['property_type'])]['agePossession'].mode()
        if not mode_value.empty:
            return mode_value.iloc[0] 
        else:
            return np.nan
    else:
        return row['agePossession']

df['agePossession'] = df.apply(mode_based_imputation, axis=1)

In [35]:
def mode_based_imputation2(row):
    if row['agePossession'] == 'Undefined':
        mode_value = df[(df['sector'] == row['sector'])]['agePossession'].mode()
        if not mode_value.empty:
            return mode_value.iloc[0] 
        else:
            return np.nan
    else:
        return row['agePossession']

df['agePossession'] = df.apply(mode_based_imputation2, axis=1)

In [36]:
def mode_based_imputation3(row):
    if row['agePossession'] == 'Undefined':
        mode_value = df[(df['property_type'] == row['property_type'])]['agePossession'].mode()
        if not mode_value.empty:
            return mode_value.iloc[0] 
        else:
            return np.nan
    else:
        return row['agePossession']

df['agePossession'] = df.apply(mode_based_imputation3, axis=1)

In [37]:
df.agePossession.value_counts()

agePossession
Relatively New        1834
Moderately Old         699
New Property           641
Old Property           381
Under Construction     298
Name: count, dtype: int64

In [38]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

# One-Hot Encoding
df_model = pd.get_dummies(
    df,
    columns=['property_type', 'agePossession'],
    drop_first=True,
    dtype=int
)

# Features and Target
X = df_model.drop(columns=['price', 'society'])
y = df_model['price']

# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Feature Scaling
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Linear Regression
model = LinearRegression()

model.fit(X_train_scaled, y_train)

# Prediction
y_pred = model.predict(X_test_scaled)


# Evaluation
r2 = r2_score(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

r2_train = r2_score(y_train, model.predict(X_train_scaled))

print(f"R² Score : {r2:.4f}")
print(f"R² Score (Train) : {r2_train:.4f}")
print(f"RMSE     : {rmse:.4f}")

R² Score : 0.8870
R² Score (Train) : 0.8716
RMSE     : 0.8645